### ISSUE TITLE
[Windows] BTM crashed while launching

### ISSUE THREAD

**Issue by atribera** [sandialabs/snl-quest#65]
BTM app crashes while getting launched from the QuESt platform. QuESt platform was launched using the `start.bat` file. This is the error in the terminal:

```
[INFO   ] [Logger      ] Record log in C:\Users\wtclark\.kivy\logs\kivy_24-12-12_5.txt
 
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.3
 
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.1
 
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
 
[INFO   ] [Kivy        ] v2.0.0
 
[INFO   ] [Kivy        ] Installed at "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\lib\site-packages\kivy\__init__.py"
 
[INFO   ] [Python      ] v3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
 
[INFO   ] [Python      ] Interpreter at "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\Scripts\python.exe"
 
[INFO   ] [Factory     ] 186 symbols loaded
 
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
 
[INFO   ] [Text        ] Provider: sdl2
 
[INFO   ] [Window      ] Provider: sdl2
 
[INFO   ] [GL          ] Using the "OpenGL" graphics system
 
[INFO   ] [GL          ] GLEW initialization succeeded
 
[INFO   ] [GL          ] Backend used <glew>
 
[INFO   ] [GL          ] OpenGL version <b'4.6.0 - Build 31.0.101.4575'>
 
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
 
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(R) Xe Graphics'>
 
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
 
[INFO   ] [GL          ] Shading version <b'4.60 - Build 31.0.101.4575'>
 
[INFO   ] [GL          ] Texture max size <16384>
 
[INFO   ] [GL          ] Texture max units <32>
 
[INFO   ] [Window      ] auto add sdl2 input provider
 
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 
Traceback (most recent call last):
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\Python39\lib\runpy.py", line 197, in _run_module_as_main
 
     return _run_code(code, main_globals, None,
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\Python39\lib\runpy.py", line 87, in _run_code
 
     exec(code, run_globals)
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\lib\site-packages\btm\__main__.py", line 59, in <module>
 
     from btm.es_gui.resources.widgets.common import MyPopup, WarningPopup, WizardCompletePopup, TileButton, RecycleViewRow, BASE_TRANSITION_DUR, BUTTON_FLASH_DUR, ANIM_STAGGER,FADEIN_DUR, SLIDER_DUR, fade_in_animation
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\lib\site-packages\btm\es_gui\resources\widgets\common.py", line 12, in <module>
 
     mpl.use('module://kivy.garden.matplotlib.backend_kivy')
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\lib\site-packages\matplotlib\__init__.py", line 1264, in use
 
     plt.switch_backend(name)
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\quest\app_envs\env_btm\lib\site-packages\matplotlib\pyplot.py", line 271, in switch_backend
 
     backend_mod = importlib.import_module(
 
   File "C:\Users\wtclark\Desktop\Quest\quest_win\Python39\lib\importlib\__init__.py", line 127, in import_module
 
     return _bootstrap._gcd_import(name[level:], package, level)
 
   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
 
   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
 
   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
 
   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
 
   File "<frozen importlib._bootstrap>", line 635, in _load_backward_compatible
 
KeyError: 'kivy.garden.matplotlib'
```

**Comment by ylpomer** [comment]
The issue is because the kivy garden package manager did not function correctly. If you are on windows open up the file explorer navigate to C:/Users/yourusername/.kivy and unzip the included garden file here. if there is an existing garden folder replace it.
[garden.zip](https://github.com/user-attachments/files/18157081/garden.zip)
